# -*- coding: utf-8 -*-
"""scikitLinearModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VfKKlEPrCW6fzx_cvIPW3wSzRH3lkvpF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv("waterdata.csv", encoding= 'unicode_escape')

dataset.describe()

dataset["Temp"] = pd.to_numeric(dataset['Temp'], errors='coerce')
dataset["Temp"] = dataset["Temp"].replace(np.nan, 0)
dataset["PH"] = pd.to_numeric(dataset['PH'], errors='coerce')
dataset["PH"] = dataset["PH"].replace(np.nan, 0)
dataset["D.O. (mg/l)"] = pd.to_numeric(dataset['D.O. (mg/l)'], errors='coerce')
dataset["D.O. (mg/l)"] = dataset["D.O. (mg/l)"].replace(np.nan, 0)
# dataset["Temp"] = dataset["Temp"].fillna()

y = dataset["D.O. (mg/l)"]

X = dataset[["Temp", "PH"]]

# X["Temp"] = X["Temp"].mean()
# X["Temp"] = X[X["Temp"]==0].mean()

# X["Temp"].mean()
X["PH"].mean()

dataset=dataset.mask(dataset["Temp"]==0).fillna(dataset["Temp"].mean())
dataset=dataset.mask(dataset["PH"]==0).fillna(dataset["PH"].mean())
dataset=dataset.mask(dataset["D.O. (mg/l)"]==0).fillna(dataset["D.O. (mg/l)"].mean())

y = dataset["D.O. (mg/l)"]
X = dataset[["Temp", "PH"]]
X["PH"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

from sklearn.linear_model import LinearRegression

lm = LinearRegression()

lm.fit(X_train, y_train)

lm.coef_

predictions = lm.predict(X_test)

# predictions
# 0.07 0.0000032

X_test.shape

data = {'longitude':  [30.6],
        'latitude': [7.5]}

df = pd.DataFrame (data, columns = ['longitude','latitude'])

df.shape

answer = lm.predict(df)

answer

